# Site settings
title: Luis E. Aguilar
email: luis.e.aguilar@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "luiseaguilar.com/"

twitter_username: 20tibbygt06
github_username:  20tibbygt06
facebook_username: 20tibbygt06
linkedin_username:
google_plus_username:

# Build settings
markdown: kramdown
highlighter: pygments
